steps:
  - name: hashicorp/terraform:1.0.1
    args:
      - init
      - -backend=true
      - -backend-config=bucket=terraform-upgrade
  - name: hashicorp/terraform:1.0.1
    args:
      - validate
  - name: hashicorp/terraform:1.0.1
    args: ["plan"]
  - name: hashicorp/terraform:1.0.1
    args: ["destroy"]